//
//  Brand.swift
//  Brands
//
//  Created by Yahia on 6/10/17.
//  Copyright © 2017 Yahia. All rights reserved.
//

import Foundation
import SwiftyJSON

public class Brand:  NSObject {
    //Auto Generated by SwiftyJSONAccelerator
    
    // MARK: Declaration for string constants to be used to decode and also serialize.
    internal let kaaBrandsInternalIdentifierKey: String = "id"
    internal let kaaBrandsLogoKey: String = "logo"
    internal let kaaBrandsNameKey: String = "name"
    
    
    // MARK: Properties
    public var ID: Int?
    public var logo: String?
    public var name: String?
    public var isSelected: Bool = false
    
    
    /**
     Initates the class based on the JSON that was passed.
     - parameter json: JSON object from SwiftyJSON.
     - returns: An initalized instance of the class.
     */
    public init(json: JSON) {
        ID = json[kaaBrandsInternalIdentifierKey].int
        logo = json[kaaBrandsLogoKey].string
        name = json[kaaBrandsNameKey].string
        
    }
    
 
    
}
