# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brands' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Brands
 
pod 'SwiftyJSON'
pod 'Toast', '~> 3.1.0'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'BEMCheckBox'
pod 'Reachability'
  target 'BrandsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrandsUITests' do
    inherit! :search_paths
    pod 'BEMCheckBox'
  end

end
